condense_wildcard_suffixes   = true
doc_comment_code_block_width = 80
edition                      = "2024"             # Keep in sync with Cargo.toml.
enum_discrim_align_threshold = 60
force_explicit_abi           = false
force_multiline_blocks       = true
format_code_in_doc_comments  = true
format_macro_matchers        = true
format_strings               = true
group_imports                = "StdExternalCrate"
hex_literal_case             = "Upper"
imports_granularity          = "Crate"
imports_layout               = "HorizontalVertical"
inline_attribute_width       = 60
match_block_trailing_comma   = true
max_width                    = 80
newline_style                = "Unix"
normalize_comments           = true
normalize_doc_attributes     = true
overflow_delimited_expr      = true
struct_field_align_threshold = 60
tab_spaces                   = 2
unstable_features            = true
use_field_init_shorthand     = true
use_try_shorthand            = true
wrap_comments                = true


