[formatting]
align_entries  = true
column_width   = 110
compact_arrays = false
reorder_keys   = true

[[rule]]
include = [ "**/Cargo.toml" ]
keys    = [ "package", "workspace.package" ]

[rule.formatting]
reorder_keys = false
