name: Publish Crates

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  publish:
    name: Publish ndg-commonmark
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo registry and index
        uses: Swatinem/rust-cache@v2

      - name: Publish ndg-commonmark
        run: |
          cargo publish -p ndg-commonmark --no-verify --locked --token ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Wait for ndg-commonmark to be available
        run: |
          for i in {1..15}; do
            sleep 10
            cargo search ndg-commonmark | grep -q ndg-commonmark && break
          done
